language: python
python:
  - "3.7"

notifications:
  email: false

sudo: false

before_install:
  - pip install Cython
  - pip install codecov
  - pip install coverage
  - pip install paddlepaddle>=1.6
  - pip install zmq

install:
  - pip install -r requirements.txt

script:
  - coverage run test.py

after_success:
  - codecov
