job_type: paddle_fl
job_config:
  program: paddle_detection
  proposal_wait_time: 5
  worker_num: 2
  max_iter: 10
  inner_step: 1
  device: cpu
  use_vdl: true
algorithm_config: ./yolov3_mobilenet_v1_fruit.yml
